### ISSUE TITLE
上传照片前压缩照片

### ISSUE THREAD

**Issue by Natt7** [uicestone/CCMeiChe#84]

**Comment by uicestone** [comment]
@supersheep 新的微信 JS API里的上传图片接口是不是可以用来客户端压缩图片的效果？是不是考虑一下做掉。

**Comment by supersheep** [comment]
搞定，相关提交：8c410724c2504552a504affd86ca76c298dcedc9 97e8780ce13184924ac60075677c4d8e8e7c1972 52c9f5607389686238c879f79aa9f3bc744107dc 4de6342ea3b19e902a4759c062736aa148f2fbdf
